spring:
  rabbitmq:
    host: rabbitmq
  boot:
    admin:
      url: http://springBootAdmin:8081
  sleuth:
    sampler:
      percentage: 1.0
management:
  context-path: /manage
  security:
    enabled: false

health:
  config:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

server:
  port: ${PORT:${SERVER_PORT:0}}