spring:
  rabbitmq:
    host: rabbitmq
  boot:
    admin:
      url: http://springBootAdmin:8081
      
management:
  context-path: /manage
  security:
    enabled: false

health:
  config:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

server:
  port: ${PORT:${SERVER_PORT:0}}