eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
management:
  security:
    enabled: false
spring:
  boot:
    admin:
      url: http://springBootAdmin:8081
health:
  config:
    enabled: false